version: '3'

services:
  btc:
    container_name: btc-service
    privileged: true 
    build: ./btc/
    volumes:
      - "./btc/btc/matchengine/config.json:/btc/matchengine/config.json"
      - "./btc/btc/accesshttp/config.json:/btc/accesshttp/config.json"
      - "./btc/btc/marketprice/config.json:/btc/marketprice/config.json"
      - "./btc/btc/accessws/config.json:/btc/accessws/config.json"
      - "./btc/btc/alertcenter/config.json:/btc/alertcenter/config.json"
      - "./btc/btc/readhistory/config.json:/btc/readhistory/config.json"
      - "./btc/tmp:/tmp/"
      - "./logs:/var/logs/trade"
      - "./btc/src/viabtc:/src/viabtc"
    ports:
      - "17416:7416"
      - "17316:7316"
      - "17317:7317"
      - "17424:7424"
      - "14444:4444"
      - "18080:8080"
      - "18081:8081"
      - "18091:8091"
    extra_hosts:
      - "dockerhost:172.21.0.1"
    depends_on:
      - mysql
      - mq
      - redis_sentinel
      - redis_slave
      - redis_master
    links:
      - mysql:db
      - mq:mq
      - redis_sentinel
      - redis_slave
      - redis_master
    
  redis_master:
    container_name: btc-redis-master
    image: redis:4.0.2-alpine
    ports:
      - "127.0.0.1:16379:6379"

  redis_slave:
    container_name: btc-redis-slave
    image: redis:4.0.2-alpine
    ports:
      - "127.0.0.1:16380:6379"

  redis_sentinel:
    container_name: btc-redis-sentinel
    build: redis
    image: redis-sentinel
    environment:
      - MASTER_NAME=mymaster
      - QUORUM=1
      - MASTER=redis_master
      - SLAVES=redis_slave
    depends_on:
      - redis_master
    ports:
      - "127.0.0.1:26379:26379"

  mysql:
    container_name: btc-mysql
    build: ./db/
    ports:
      - "127.0.0.1:13306:3306"

  zookeeper:
    container_name: btc-zookeeper
    image: wurstmeister/zookeeper
    ports:
      - "127.0.0.1:12181:2181"

  mq:
    container_name: btc-kafka
    image: wurstmeister/kafka
    links:
      - zookeeper
    ports:
      - "127.0.0.1:19092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: mq
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  
  nginx:
    image: nginx
    volumes:
      - "./nginx/sites-enabled/socket.conf:/etc/nginx/conf.d/socket.conf"
      #宿主机和容器之间的目录映射，保持一致，这样方便支持ssl，容器可以读宿主机的ssl文件#
      - "/viabtc_exchange_server_docker_with_nginx/nginx/sites-enabled:/viabtc_exchange_server_docker_with_nginx/nginx/sites-enabled"
      - "./btc/tmp:/sockets"
    ports:
      - "8008:8008"

